remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# title: blank
title: Andrey's
# blank # the website title (if blank, full name will be used instead)
# first_name: Andrey's
# middle_name: M.
# last_name: M.
email: andreymikhit@icloude.com
logo: /assets/img/my_github_photo.jfif
description: projects @GitHub
# description: > # the ">" symbol means to ignore newlines until "footer_text:"
#  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
#footer_text: >
#  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
#  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
#  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: portfolio-website, python, jupyter, IT, Azure, SQL, Debian # add your own keywords or leave empty
lang: en, de, ru # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)
#url: https://alshedivat.github.io # the base hostname & protocol for your site
#baseurl: /al-folio # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: https://gdpr.eu/tag/gdpr/ # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
#back_to_top: true # set to false to disable the back to top button
