# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Andrey's GitHub 
description: projects @GitHub
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
theme: jekyll-theme-minimal
#remote_theme: pages-themes/minimal@v0.2.0
#- jekyll-remote-theme # add this line to the plugins list if you already have one

# GitHub CLI api
# https://cli.github.com/manual/gh_api
gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /orgs/ORG/repos
